//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.5.3
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>DestinationPair</summary>
	[PublishedModel("destinationPair")]
	public partial class DestinationPair : PublishedContentModel, IRedirect301
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		public new const string ModelTypeAlias = "destinationPair";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DestinationPair, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public DestinationPair(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Currency
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		[ImplementPropertyType("currency")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent Currency => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("currency");

		///<summary>
		/// Destination
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		[ImplementPropertyType("destination")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent Destination => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("destination");

		///<summary>
		/// End Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		[ImplementPropertyType("endDate")]
		public global::System.DateTime EndDate => this.Value<global::System.DateTime>("endDate");

		///<summary>
		/// Free Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		[ImplementPropertyType("freeText")]
		public string FreeText => this.Value<string>("freeText");

		///<summary>
		/// IsInStock
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		[ImplementPropertyType("isInStock")]
		public bool IsInStock => this.Value<bool>("isInStock");

		///<summary>
		/// Price
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		[ImplementPropertyType("price")]
		public decimal Price => this.Value<decimal>("price");

		///<summary>
		/// Start Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		[ImplementPropertyType("startDate")]
		public global::System.DateTime StartDate => this.Value<global::System.DateTime>("startDate");

		///<summary>
		/// Expiration Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		[ImplementPropertyType("expirationDate")]
		public global::System.DateTime ExpirationDate => global::Umbraco.Web.PublishedModels.Redirect301.GetExpirationDate(this);

		///<summary>
		/// Uniform Resource Locator
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		[ImplementPropertyType("UniformResourceLocator")]
		public global::Umbraco.Web.Models.Link UniformResourceLocator => global::Umbraco.Web.PublishedModels.Redirect301.GetUniformResourceLocator(this);
	}
}
