//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.5.3
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "redirect301"
	/// <summary>301</summary>
	public partial interface IRedirect301 : IPublishedContent
	{
		/// <summary>Expiration Date</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		global::System.DateTime ExpirationDate { get; }

		/// <summary>Uniform Resource Locator</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		global::Umbraco.Web.Models.Link UniformResourceLocator { get; }
	}

	/// <summary>301</summary>
	[PublishedModel("redirect301")]
	public partial class Redirect301 : PublishedContentModel, IRedirect301
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		public new const string ModelTypeAlias = "redirect301";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Redirect301, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Redirect301(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Expiration Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		[ImplementPropertyType("expirationDate")]
		public global::System.DateTime ExpirationDate => GetExpirationDate(this);

		/// <summary>Static getter for Expiration Date</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		public static global::System.DateTime GetExpirationDate(IRedirect301 that) => that.Value<global::System.DateTime>("expirationDate");

		///<summary>
		/// Uniform Resource Locator
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		[ImplementPropertyType("UniformResourceLocator")]
		public global::Umbraco.Web.Models.Link UniformResourceLocator => GetUniformResourceLocator(this);

		/// <summary>Static getter for Uniform Resource Locator</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		public static global::Umbraco.Web.Models.Link GetUniformResourceLocator(IRedirect301 that) => that.Value<global::Umbraco.Web.Models.Link>("UniformResourceLocator");
	}
}
